### ISSUE TITLE
.NET8 ServiceScoped Disposing Singleton instances

### ISSUE THREAD

**Issue by stephenlautier** [ipjohnson/Grace#316] opened 2024-02-13 23:25 UTC
I'll open this new issue maybe to help me figure out why its being caused, or if its a bug (seems more like a bug though)
Specifically, I'm using jods4:net8 PR branches (in order to use .net8/orleans8) cc: @jods4 

In short it seems that a Singleton (Keyed) is being disposed, when a `ServiceScope` e.g. via `provider.CreateScope()` is being disposed
Using the Microsoft default DI doesn't seem to cause this issue, hence why I believe its a Grace issue

I managed to narrow it a little bit in a sample app I put together from the dotnet samples/orleans (alto im trying to replicate it in a unit test, however, so far not managing to replicate it)

#### Orleans source pointing 
These are the key stuff of Orleans how they are done (which are causing the issue)
- DI registration [AddGrainStorage](https://github.com/dotnet/orleans/blob/main/src/Orleans.Runtime/Hosting/StorageProviderHostExtensions.cs#L29) > [AddMemoryGrainStorage](https://github.com/dotnet/orleans/blob/main/src/Orleans.Persistence.Memory/Hosting/MemoryGrainStorageSiloBuilderExtensions.cs#L67)
- [MemoryGrainStorage](https://github.com/dotnet/orleans/blob/main/src/Orleans.Persistence.Memory/Storage/MemoryStorage.cs#L128)  which implements the `IDispose`
- This is were the dispose of the Scope happens https://github.com/dotnet/orleans/blob/main/src/Orleans.Runtime/Catalog/ActivationData.cs#L743

### Sample
- clone `git clone https://github.com/stephenlautier/dotnet.samples.git --branch feature/grace-sample` (projects already pointing to Grace source)
- Simply run `AdventureServer`

#### Replicating it
- *after the above*
- Add a breakpoint in `MemoryGrainStorage.Dispose` (which is not in the project, its Orleans) - NOTE: Disable `Just my code`
- Wait around seconds 3-5sec - cause i set Grain (which is Scoped) to deactivate which internally then disposes the service
  - Pressing any key then will continue, which will call again another function and will throw an exception as the `MemoryGrainStorage` is disposed
  - Repeating the above with `UseGrace` commented will work as expected

### Grace unit test
This is the unit test i created, however **IT DOES NOT** replicate the issue (yet), im just adding it as a starting point for now
https://github.com/stephenlautier/Grace.DependencyInjection.Extensions/blob/net8-test/test/Grace.DependencyInjection.Extensions.Tests/GraceContainerTests.cs#L51

UPDATE: 
Using .NET8 + jods:net8 branch + orleans7 **does not replicate** it either - in orleans8 they switched to Keyed services (from custom implementation in orleans7<=); so potentially it has to do something with Keyed services (and again this one is keyed singleton)

**Comment by stephenlautier** [comment] 2024-02-14 11:11
I managed to replicate it in the unit test finally!

To replicate, its a specific scenario
- `AddKeyedSingleton` using the factory method e.g. `.AddKeyedSingleton<StrategyIndex>("hots", (provider, o) => new());`
    - Using `AddSingleton`/`AddKeyedSingleton<StrategyIndex>("hots")` wont dispose
- Create new DI scope
- Resolve keyed singleton through DI scope (NOTE: if it was resolved BEFORE, it won't happen)

Unit test: https://github.com/stephenlautier/Grace.DependencyInjection.Extensions/blob/net8-test/test/Grace.DependencyInjection.Extensions.Tests/GraceContainerTests.cs#L51

**Comment by jods4** [comment] 2024-02-15 01:08
@stephenlautier thanks for the test, it really helps.

Good news: I have been able to simplify your test into pure Grace code (I removed MS DI) and can reproduce it.
I gave it a quick look with a debugger and I think I know why the singleton is added to the wrong disposal scope during creation.
I'm not sure if it's a regression caused by the changes I made to support any-key-singletons, it could be.

I need a little more time to fix it but I will.

**Comment by stephenlautier** [comment] 2024-02-15 10:29
@jods4 thanks!
Not entirely sure either if its a key registration by grace even in the previous versions (though we use them extensively and never had an issue, not sure if we simply didnt notice though) or a regression 

Sure thing, if you manage to fix it let me know, and I can give it a test run 🚀

**Comment by jods4** [comment] 2024-02-16 00:06
@stephenlautier It should be fixed on `net8` branch.

It's actually a bug in the `DeferredSingleton` lifestyle in Grace 7.0 as well, I added a test case that demonstrates this.
Disposable services using that lifestyle are registered in the scope where they are resolved, rather than the scope where they are exported.

I suppose it was unnoticed for so long because `DeferredSingleton` is a rarely used lifestyle (you need to call `LifeStyle.Custom()` in order to use it + you need to register an `IDisposable` service + you need to resolve it in a child scope. A pretty uncommon situation, I suppose.

It is more visible now, because I internally reused the `DeferredSingleton` when registering singleton services that import the injected key. This is a new feature of Grace 8 (so no regression), and I inherited the existing bug.
BTW I think I will be able to optimize things so that I don't have to use the `DeferredSingleton` in this situation anyway.

**Closed by jods4** 2024-02-16 00:06 UTC

**Comment by stephenlautier** [comment] 2024-02-16 00:34
@jods4 Many thanks!

Good to know the issue exists already also, tomorrow I will get latest from your branches and test it out, thanks once again 🙏
